### ISSUE TITLE
table thead

### ISSUE THREAD

**Issue by rodrigoEclipsa** [aminpaks/angular-virtual-list#1]
Support table with header?

**Comment by aminpaks** [comment]
Hi,

Are you referring to `table` tag with a sticky header?

**Comment by rodrigoEclipsa** [comment]
Sorry for the little information, I mean if it is possible to put a thead segment to the sticky table or not, since the original component that this forked has problems in to do this

**Comment by aminpaks** [comment]
Well simply is very difficult to create a sticky header with original `table` tag in HTML. But if you do it with `div` tag and use `flexbox` as your layout will work.
I'll try to add this as another example to demo soon.

**Comment by aminpaks** [comment]
I added a sample to [live demo](https://aminpaks.github.io/angular-virtual-list/demo/dist/) of what you are looking for, hopefully it's satisfactory.

Good luck.

**Comment by rodrigoEclipsa** [comment]
You are great !!. Try to make it work with a table structure but without success
