### ISSUE TITLE
Not working for angular js 1.6

### ISSUE THREAD

**Issue by mkrishna2025** [aminpaks/angular-virtual-list#2]
I am getting below error while installing this module.... Can any one please guide me on this....

ERROR in ./~/angular-virtual-list/dist/bundles/angular-virtual-list.umd.js
Module not found: Error: Cannot resolve module '@angular/core' in /home/bart/Development/DevTest/BartDev/node_modules/angular-virtual-list/dist/bundles
 @ ./~/angular-virtual-list/dist/bundles/angular-virtual-list.umd.js 2:81-105

ERROR in ./~/angular-virtual-list/dist/bundles/angular-virtual-list.umd.js
Module not found: Error: Cannot resolve module '@angular/common' in /home/bart/Development/DevTest/BartDev/node_modules/angular-virtual-list/dist/bundles
 @ ./~/angular-virtual-list/dist/bundles/angular-virtual-list.umd.js 2:107-133

ERROR in ./~/angular-virtual-list/dist/bundles/angular-virtual-list.umd.js
Module not found: Error: Cannot resolve module 'rxjs/add/operator/filter' in /home/bart/Development/DevTest/BartDev/node_modules/angular-virtual-list/dist/bundles
 @ ./~/angular-virtual-list/dist/bundles/angular-virtual-list.umd.js 2:135-170

ERROR in ./~/angular-virtual-list/dist/bundles/angular-virtual-list.umd.js
Module not found: Error: Cannot resolve module 'rxjs/add/operator/takeUntil' in /home/bart/Development/DevTest/BartDev/node_modules/angular-virtual-list/dist/bundles
 @ ./~/angular-virtual-list/dist/bundles/angular-virtual-list.umd.js 2:172-210

**Comment by aminpaks** [comment]
This package is not for AngularJs, it requires Angular v4.x

**Comment by aminpaks** [comment]
I'm closing this issue because it's not related to this package.
