### ISSUE TITLE
(questions) Reactive Forms Array

### ISSUE THREAD

**Issue by borriej** [aminpaks/angular-virtual-list#4]
Hi,

Can your module be used with a reactive forms array? Since reactive form, form array is dependent on index.

How does your module differ from the original?

Is it possible to use the body instead of a fixed container scroll?

**Comment by aminpaks** [comment]
The only difference this version has compare to the original is the source of the list is an observable. Also I changed some of the feature for calculation of height. That's it.

Not sure what do you mean by "form array", also you won't be able to run it under body tag out of box if that's what you mean.

**Comment by borriej** [comment]
ok thank you! That makes it more clear.
