### ISSUE TITLE
CTRL + F not working in virtual list

### ISSUE THREAD

**Issue by vaibhav2009** [aminpaks/angular-virtual-list#6]
Let me explain it with an example-Suppose I am having a list of say ten thousand data and I want to use search in the page( i.e. ctrl +f) functionality of browser to search data that might be present at the end of the list. So, using ctrl+f to search that data is not working on the list.

**Comment by aminpaks** [comment]
Hi,

Of course searching for items won't work with the native browser search. All type of virtual scroll by nature try to not load all the items into browser DOM, therefore user cannot find the items that are not within the viewport.

The easiest way to implement this feature is by creating a search field to look-up the list and either filter the items or scroll into them (first is better than second). Both can be done by you and it's very simple to implement.

IMHO this feature could be part of core part of this project but unfortunately I don't have too much time to spend on it. A PR is always welcome.

**Comment by vaibhav2009** [comment]
I don't want to disable default CTRL+F behavior of browser, so is there any way to catch the keys input in Ctrl+f dialog box? so that, I can try to search the keys in my list that is not rendered in the DOM and populate them accordingly.

**Comment by aminpaks** [comment]
Sure. You can always listen for `onKeyPress` on `document` and handle the filtering. It must be simple.

https://www.w3schools.com/jsref/event_onkeypress.asp

**Comment by aminpaks** [comment]
JFYI, I don't think you can catch the native browser search events.

**Comment by vaibhav2009** [comment]
Exactly, when browser's search dialog box is opened, onKeyPress event is being disabled at the code. Do we have any other scrollbar in which we can populate huge data without making UI lag and also make default  ctrl+f work?

**Comment by aminpaks** [comment]
Unfortunately I do not.
